name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: npm run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          version: latest
      - run: npm ci
      - run: npm run test
  add:
    name: npm add donovanglover/base16-tailwind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          version: latest
      - run: mkdir test && cd test && npm init -y
      - run: npm add donovanglover/base16-tailwind
