name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: npm run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          version: latest
      - run: npm ci
      - run: npm run test
  test-without-coverage:
    name: npm run test-without-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          version: latest
      - run: npm ci
      - run: npm run test-without-coverage
  add:
    name: npm add donovanglover/base16-tailwind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          version: latest
      - run: mkdir test && cd test && npm init -y
      - run: npm add donovanglover/base16-tailwind
  lint:
    name: npm run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          version: latest
      - run: npm ci
      - run: npm run lint
  audit:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          version: latest
      - run: npm audit
  publish:
    name: deno publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          version: latest
      - run: deno task prepare
      - run: deno publish
